import { NextRequest } from 'next/server';
import { AccountsHttpError,isAuthFailure,jsonError,jsonSuccess,mapPgError,requireAccountsAccess } from '@/src/lib/accounts/auth';
import { writeFinancialAudit } from '@/src/lib/accounts/audit';
import { loadSupplierInvoiceType,serializeSupplierInvoiceType,updateSupplierInvoiceType } from '@/src/lib/accounts/supplier-invoice-types';
import { SUPPLIER_PAYABLES_CAPABILITIES,assertSupplierPayablesCapability } from '@/src/lib/accounts/supplier-payables-access';
import { withTransaction } from '@/src/lib/accounts/with-transaction';
type Ctx={params:Promise<{id:string}>};
export async function GET(request:NextRequest,context:Ctx){const auth=await requireAccountsAccess(request);if(isAuthFailure(auth))return auth.response;try{await assertSupplierPayablesCapability(null,auth.user.id,SUPPLIER_PAYABLES_CAPABILITIES.VIEW);const {id}=await context.params;const row=await withTransaction(client=>loadSupplierInvoiceType(client,id));return jsonSuccess({data:serializeSupplierInvoiceType(row)});}catch(error){return error instanceof AccountsHttpError?jsonError(error.message,error.status):mapPgError(error);}}
export async function PATCH(request:NextRequest,context:Ctx){const auth=await requireAccountsAccess(request);if(isAuthFailure(auth))return auth.response;try{const {id}=await context.params;const body=await request.json();const row=await withTransaction(async client=>{await assertSupplierPayablesCapability(client,auth.user.id,SUPPLIER_PAYABLES_CAPABILITIES.INVOICE_TYPES_MANAGE);const before=await loadSupplierInvoiceType(client,id);const r=await updateSupplierInvoiceType(client,{id,userId:auth.user.id,...body});await writeFinancialAudit(client,{userId:auth.user.id,action:'SUPPLIER_INVOICE_TYPE_UPDATED',entityType:'supplier_invoice_type',entityId:id,oldValues:serializeSupplierInvoiceType(before),newValues:serializeSupplierInvoiceType(r),description:`تعديل نوع فاتورة ${r.code}`,ipAddress:auth.ipAddress,userAgent:auth.userAgent});return r;});return jsonSuccess({data:serializeSupplierInvoiceType(row)});}catch(error){return error instanceof AccountsHttpError?jsonError(error.message,error.status):mapPgError(error);}}
