import { NextRequest } from 'next/server';
import { AccountsHttpError,isAuthFailure,jsonError,jsonSuccess,mapPgError,requireAccountsAccess } from '@/src/lib/accounts/auth';
import { writeFinancialAudit } from '@/src/lib/accounts/audit';
import { loadSupplierInvoice,serializeSupplierInvoice,updateSupplierInvoice } from '@/src/lib/accounts/supplier-invoices';
import { SUPPLIER_PAYABLES_CAPABILITIES,assertSupplierPayablesCapability } from '@/src/lib/accounts/supplier-payables-access';
import { withTransaction } from '@/src/lib/accounts/with-transaction';
import { query } from '@/src/lib/db';
type Ctx={params:Promise<{id:string}>};
export async function GET(request:NextRequest,context:Ctx){const auth=await requireAccountsAccess(request);if(isAuthFailure(auth))return auth.response;try{await assertSupplierPayablesCapability(null,auth.user.id,SUPPLIER_PAYABLES_CAPABILITIES.VIEW);const {id}=await context.params;const r=await query(`SELECT si.*,s.name_ar supplier_name_ar,s.supplier_number,sa.account_number,eg.code expense_gl_code,eg.name_ar expense_gl_name_ar,pg.code payable_gl_code,cc.code cost_center_code,cc.name_ar cost_center_name_ar,sit.code invoice_type_code,sit.name_ar invoice_type_name_ar,je.entry_number journal_entry_number,rje.entry_number reversal_journal_entry_number FROM accounts.supplier_invoices si JOIN accounts.suppliers s ON s.id=si.supplier_id JOIN accounts.supplier_accounts sa ON sa.id=si.supplier_account_id LEFT JOIN accounts.chart_of_accounts eg ON eg.id=si.expense_gl_account_id LEFT JOIN accounts.chart_of_accounts pg ON pg.id=sa.payable_gl_account_id LEFT JOIN accounts.cost_centers cc ON cc.id=si.cost_center_id LEFT JOIN accounts.supplier_invoice_types sit ON sit.id=si.invoice_type_id LEFT JOIN accounts.journal_entries je ON je.id=si.journal_entry_id LEFT JOIN accounts.journal_entries rje ON rje.id=si.reversal_journal_entry_id WHERE si.id=$1::uuid`,[id]);if(!r.rows[0])return jsonError('فاتورة المورد غير موجودة',404);return jsonSuccess({data:serializeSupplierInvoice(r.rows[0] as Parameters<typeof serializeSupplierInvoice>[0])});}catch(error){return error instanceof AccountsHttpError?jsonError(error.message,error.status):mapPgError(error);}}
export async function PATCH(request:NextRequest,context:Ctx){const auth=await requireAccountsAccess(request);if(isAuthFailure(auth))return auth.response;try{const {id}=await context.params;const body=await request.json();const row=await withTransaction(async client=>{await assertSupplierPayablesCapability(client,auth.user.id,SUPPLIER_PAYABLES_CAPABILITIES.INVOICES_PREPARE);const before=await loadSupplierInvoice(client,id);const r=await updateSupplierInvoice(client,{id,userId:auth.user.id,...body});await writeFinancialAudit(client,{userId:auth.user.id,action:'SUPPLIER_INVOICE_UPDATED',entityType:'supplier_invoice',entityId:id,oldValues:serializeSupplierInvoice(before),newValues:serializeSupplierInvoice(r),description:`تعديل فاتورة مورد ${r.invoice_number}`,ipAddress:auth.ipAddress,userAgent:auth.userAgent});return r;});return jsonSuccess({data:serializeSupplierInvoice(row)});}catch(error){return error instanceof AccountsHttpError?jsonError(error.message,error.status):mapPgError(error);}}
