import type { TxClient } from './with-transaction';
import { txQuery } from './with-transaction';

export type AuditAction =
  | 'fiscal_year.create'
  | 'fiscal_year.update'
  | 'fiscal_year.set_default'
  | 'fiscal_year.activate'
  | 'fiscal_year.close'
  | 'fiscal_year.delete'
  | 'fiscal_period.create'
  | 'fiscal_period.update'
  | 'fiscal_period.open'
  | 'fiscal_period.close'
  | 'fiscal_period.lock'
  | 'fiscal_period.reopen'
  | 'fiscal_period.delete'
  | 'cost_center.create'
  | 'cost_center.update'
  | 'cost_center.toggle_status'
  | 'cost_center.delete'
  | 'document_sequence.update'
  | 'chart_account.create'
  | 'chart_account.update'
  | 'chart_account.move'
  | 'chart_account.toggle_status'
  | 'chart_account.delete'
  | 'chart_account.seed'
  | 'journal_entry.created'
  | 'journal_entry.updated'
  | 'journal_entry.deleted'
  | 'journal_entry.submitted'
  | 'journal_entry.reviewed'
  | 'journal_entry.approved'
  | 'journal_entry.rejected'
  | 'journal_entry.returned_to_draft'
  | 'journal_entry.cancelled'
  | 'journal_entry.posted'
  | 'journal_entry.reversed'
  | 'cash_box.created'
  | 'cash_box.updated'
  | 'cash_box.activated'
  | 'cash_box.suspended'
  | 'cash_box.closed'
  | 'cash_box.custodian_assigned'
  | 'cash_box.custodian_removed'
  | 'cash_box.variance_settings_updated'
  | 'cash_session.opened'
  | 'cash_session.closing_started'
  | 'cash_session.count_recorded'
  | 'cash_session.closing_cancelled'
  | 'cash_session.closed'
  | 'cash_count_adjustment.created'
  | 'cash_count_adjustment.posted'
  | 'cash_session.closed_after_adjustment'
  | 'cash_voucher.created'
  | 'cash_voucher.updated'
  | 'cash_voucher.posted'
  | 'cash_voucher.voided'
  | 'cash_voucher.deleted'
  | 'cash_transfer.created'
  | 'cash_transfer.updated'
  | 'cash_transfer.dispatched'
  | 'cash_transfer.received'
  | 'cash_transfer.cancelled'
  | 'bank.created'
  | 'bank.updated'
  | 'bank.deactivated'
  | 'bank_branch.created'
  | 'bank_branch.updated'
  | 'bank_branch.deactivated'
  | 'bank_account.created'
  | 'bank_account.updated'
  | 'bank_account.suspended'
  | 'bank_account.activated'
  | 'bank_account.closed'
  | 'bank_account.user_assigned'
  | 'bank_account.user_removed'
  | 'bank_voucher.created'
  | 'bank_voucher.updated'
  | 'bank_voucher.posted'
  | 'bank_voucher.voided'
  | 'bank_voucher.deleted'
  | 'bank_transfer.created'
  | 'bank_transfer.updated'
  | 'bank_transfer.posted'
  | 'bank_transfer.voided'
  | 'bank_transfer.deleted'
  | 'bank_statement.created'
  | 'bank_statement.updated'
  | 'bank_statement.started'
  | 'bank_statement.cancelled'
  | 'bank_statement.reconciled'
  | 'bank_statement.closed'
  | 'bank_statement.reopened'
  | 'bank_statement.csv_imported'
  | 'bank_statement.line_added'
  | 'bank_statement.line_updated'
  | 'bank_statement.line_deleted'
  | 'bank_statement.line_excluded'
  | 'bank_statement.line_unexcluded'
  | 'bank_reconciliation.matched'
  | 'bank_reconciliation.match_removed'
  | 'bank_reconciliation.adjustment_posted'
  | 'student_account.created'
  | 'student_account.updated'
  | 'student_account.suspended'
  | 'student_account.activated'
  | 'student_account.closed'
  | 'student_fee_type.created'
  | 'student_fee_type.updated'
  | 'student_fee_type.deactivated'
  | 'student_charge.created'
  | 'student_charge.updated'
  | 'student_charge.posted'
  | 'student_charge.voided'
  | 'asset_category.created'
  | 'asset_category.updated'
  | 'asset_category.toggle_status'
  | 'asset_location.created'
  | 'asset_location.updated'
  | 'asset_location.toggle_status'
  | 'fixed_asset.created'
  | 'fixed_asset.updated'
  | 'fixed_asset.activated'
  | 'fixed_asset.suspended'
  | 'fixed_asset.reactivated'
  | 'fixed_asset.cancelled'
  | 'fixed_asset.capitalized_from_purchasing'
  | 'fixed_asset.threshold_overridden'
  | 'asset_movement.created'
  | 'asset_movement.posted'
  | 'asset_movement.voided'
  | 'depreciation_run.created'
  | 'depreciation_run.calculated'
  | 'depreciation_run.posted'
  | 'depreciation_run.voided'
  | 'asset_disposal.created'
  | 'asset_disposal.posted'
  | 'asset_disposal.voided'
  | 'payroll_calendar.created'
  | 'payroll_calendar.updated'
  | 'payroll_calendar.activated'
  | 'payroll_calendar.deactivated'
  | 'payroll_person.created'
  | 'payroll_person.updated'
  | 'payroll_person.suspended'
  | 'payroll_person.activated'
  | 'payroll_person.terminated'
  | 'payroll_contract.created'
  | 'payroll_contract.updated'
  | 'payroll_contract.activated'
  | 'payroll_contract.suspended'
  | 'payroll_contract.terminated'
  | 'payroll_contract.cancelled'
  | 'payroll_assignment.created'
  | 'payroll_assignment.updated'
  | 'payroll_assignment.activated'
  | 'payroll_assignment.deactivated'
  | 'payroll_component.created'
  | 'payroll_component.updated'
  | 'payroll_component.activated'
  | 'payroll_component.deactivated'
  | 'payroll_component_assignment.created'
  | 'payroll_component_assignment.updated'
  | 'payroll_component_assignment.activated'
  | 'payroll_component_assignment.deactivated'
  | 'payroll_account_mapping.created'
  | 'payroll_account_mapping.updated'
  | 'payroll_account_mapping.activated'
  | 'payroll_account_mapping.deactivated';

export async function writeFinancialAudit(
  client: TxClient,
  params: {
    userId: string;
    action: AuditAction | string;
    entityType: string;
    entityId: string;
    oldValues?: unknown;
    newValues?: unknown;
    description?: string;
    ipAddress?: string;
    userAgent?: string;
  }
): Promise<void> {
  await txQuery(
    client,
    `INSERT INTO accounts.financial_audit_log
      (user_id, action, entity_type, entity_id, old_values, new_values, description, ip_address, user_agent)
     VALUES ($1, $2, $3, $4, $5::jsonb, $6::jsonb, $7, $8, $9)`,
    [
      params.userId,
      params.action,
      params.entityType,
      params.entityId,
      params.oldValues == null ? null : JSON.stringify(params.oldValues),
      params.newValues == null ? null : JSON.stringify(params.newValues),
      params.description ?? null,
      params.ipAddress ?? null,
      params.userAgent ?? null,
    ]
  );
}
