export type SeedAccountDef = {
  code: string;
  name_ar: string;
  name_en?: string;
  type: 'ASSET' | 'LIABILITY' | 'EQUITY' | 'REVENUE' | 'EXPENSE';
  parent_code: string | null;
  is_group: boolean;
  requires_cost_center: boolean;
  /** Override natural balance; default from type. Use CREDIT for depreciation contra-asset 1300-1360 */
  normal_balance?: 'DEBIT' | 'CREDIT';
  /** ترتيب بين الأشقاء؛ يُحسب تلقائياً إن لم يُمرَّر */
  sort_order?: number;
};

/** يعيّن sort_order حسب ترتيب الظهور تحت كل أب */
export function assignSiblingSortOrders(defs: SeedAccountDef[]): SeedAccountDef[] {
  const counters = new Map<string, number>();
  return defs.map((d) => {
    if (d.sort_order != null && d.sort_order > 0) return { ...d };
    const key = d.parent_code ?? '';
    const next = (counters.get(key) || 0) + 1;
    counters.set(key, next);
    return { ...d, sort_order: next };
  });
}

/** Default college chart of accounts (parents before children). */
const COLLEGE_CHART_SEED_RAW: SeedAccountDef[] = [
  // ─── 1000 Assets ─────────────────────────────────────────────
  {
    code: '1000',
    name_ar: 'الأصول',
    name_en: 'Assets',
    type: 'ASSET',
    parent_code: null,
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '1100',
    name_ar: 'الأصول المتداولة',
    name_en: 'Current Assets',
    type: 'ASSET',
    parent_code: '1000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '1110',
    name_ar: 'النقدية',
    name_en: 'Cash',
    type: 'ASSET',
    parent_code: '1100',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '1111',
    name_ar: 'الصندوق الرئيسي',
    name_en: 'Main Cash Box',
    type: 'ASSET',
    parent_code: '1110',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1112',
    name_ar: 'صندوق الأقساط',
    name_en: 'Installments Cash Box',
    type: 'ASSET',
    parent_code: '1110',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1113',
    name_ar: 'صندوق المصروفات النثرية',
    name_en: 'Petty Cash',
    type: 'ASSET',
    parent_code: '1110',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1114',
    name_ar: 'صناديق فرعية',
    name_en: 'Sub Cash Boxes',
    type: 'ASSET',
    parent_code: '1110',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1120',
    name_ar: 'الحسابات المصرفية',
    name_en: 'Bank Accounts',
    type: 'ASSET',
    parent_code: '1100',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '1121',
    name_ar: 'الحساب المصرفي الرئيسي',
    name_en: 'Main Bank Account',
    type: 'ASSET',
    parent_code: '1120',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1122',
    name_ar: 'حساب مصرفي آخر',
    name_en: 'Other Bank Account',
    type: 'ASSET',
    parent_code: '1120',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1130',
    name_ar: 'الذمم المدينة',
    name_en: 'Receivables',
    type: 'ASSET',
    parent_code: '1100',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '1131',
    name_ar: 'ذمم الطلبة',
    name_en: 'Student Receivables',
    type: 'ASSET',
    parent_code: '1130',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1132',
    name_ar: 'أقساط طلبة مستحقة',
    name_en: 'Student Installments Due',
    type: 'ASSET',
    parent_code: '1130',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1133',
    name_ar: 'ذمم موظفين',
    name_en: 'Employee Receivables',
    type: 'ASSET',
    parent_code: '1130',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1134',
    name_ar: 'ذمم أخرى',
    name_en: 'Other Receivables',
    type: 'ASSET',
    parent_code: '1130',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1140',
    name_ar: 'السلف والعهد',
    name_en: 'Advances & Custodies',
    type: 'ASSET',
    parent_code: '1100',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '1141',
    name_ar: 'سلف الموظفين',
    name_en: 'Staff Advances',
    type: 'ASSET',
    parent_code: '1140',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1142',
    name_ar: 'سلف التدريسيين',
    name_en: 'Teacher Advances',
    type: 'ASSET',
    parent_code: '1140',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1143',
    name_ar: 'العهد النقدية',
    name_en: 'Cash Custodies',
    type: 'ASSET',
    parent_code: '1140',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1144',
    name_ar: 'العهد العينية',
    name_en: 'In-Kind Custodies',
    type: 'ASSET',
    parent_code: '1140',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1145',
    name_ar: 'سلف الأنشطة',
    name_en: 'Activity Advances',
    type: 'ASSET',
    parent_code: '1140',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1146',
    name_ar: 'سلف المشتريات',
    name_en: 'Purchase Advances',
    type: 'ASSET',
    parent_code: '1140',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1150',
    name_ar: 'المصروفات المدفوعة مقدماً',
    name_en: 'Prepaid Expenses',
    type: 'ASSET',
    parent_code: '1100',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '1151',
    name_ar: 'إيجارات مدفوعة مقدماً',
    name_en: 'Prepaid Rent',
    type: 'ASSET',
    parent_code: '1150',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1152',
    name_ar: 'اشتراكات مدفوعة مقدماً',
    name_en: 'Prepaid Subscriptions',
    type: 'ASSET',
    parent_code: '1150',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1153',
    name_ar: 'تأمين مدفوع مقدماً',
    name_en: 'Prepaid Insurance',
    type: 'ASSET',
    parent_code: '1150',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1154',
    name_ar: 'مصروفات مقدمة أخرى',
    name_en: 'Other Prepaid Expenses',
    type: 'ASSET',
    parent_code: '1150',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1200',
    name_ar: 'الأصول الثابتة',
    name_en: 'Fixed Assets',
    type: 'ASSET',
    parent_code: '1000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '1210',
    name_ar: 'الأراضي',
    name_en: 'Land',
    type: 'ASSET',
    parent_code: '1200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1220',
    name_ar: 'المباني',
    name_en: 'Buildings',
    type: 'ASSET',
    parent_code: '1200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1230',
    name_ar: 'التحسينات والترميمات الرأسمالية',
    name_en: 'Capital Improvements',
    type: 'ASSET',
    parent_code: '1200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1240',
    name_ar: 'الأثاث',
    name_en: 'Furniture',
    type: 'ASSET',
    parent_code: '1200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1250',
    name_ar: 'الأجهزة والحاسبات',
    name_en: 'Equipment & Computers',
    type: 'ASSET',
    parent_code: '1200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1260',
    name_ar: 'الأجهزة المختبرية',
    name_en: 'Lab Equipment',
    type: 'ASSET',
    parent_code: '1200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1270',
    name_ar: 'المركبات ووسائط النقل',
    name_en: 'Vehicles',
    type: 'ASSET',
    parent_code: '1200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1280',
    name_ar: 'أجهزة الاتصالات والشبكات',
    name_en: 'Network & Comms Equipment',
    type: 'ASSET',
    parent_code: '1200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1290',
    name_ar: 'أصول ثابتة أخرى',
    name_en: 'Other Fixed Assets',
    type: 'ASSET',
    parent_code: '1200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '1300',
    name_ar: 'مجمع الإهلاك',
    name_en: 'Accumulated Depreciation',
    type: 'ASSET',
    parent_code: '1000',
    is_group: true,
    requires_cost_center: false,
    normal_balance: 'CREDIT',
  },
  {
    code: '1310',
    name_ar: 'مجمع إهلاك المباني',
    name_en: 'Accum. Dep. Buildings',
    type: 'ASSET',
    parent_code: '1300',
    is_group: false,
    requires_cost_center: false,
    normal_balance: 'CREDIT',
  },
  {
    code: '1320',
    name_ar: 'مجمع إهلاك الأثاث',
    name_en: 'Accum. Dep. Furniture',
    type: 'ASSET',
    parent_code: '1300',
    is_group: false,
    requires_cost_center: false,
    normal_balance: 'CREDIT',
  },
  {
    code: '1330',
    name_ar: 'مجمع إهلاك الأجهزة والحاسبات',
    name_en: 'Accum. Dep. Equipment',
    type: 'ASSET',
    parent_code: '1300',
    is_group: false,
    requires_cost_center: false,
    normal_balance: 'CREDIT',
  },
  {
    code: '1340',
    name_ar: 'مجمع إهلاك الأجهزة المختبرية',
    name_en: 'Accum. Dep. Lab Equipment',
    type: 'ASSET',
    parent_code: '1300',
    is_group: false,
    requires_cost_center: false,
    normal_balance: 'CREDIT',
  },
  {
    code: '1350',
    name_ar: 'مجمع إهلاك المركبات',
    name_en: 'Accum. Dep. Vehicles',
    type: 'ASSET',
    parent_code: '1300',
    is_group: false,
    requires_cost_center: false,
    normal_balance: 'CREDIT',
  },
  {
    code: '1360',
    name_ar: 'مجمع إهلاك الأصول الأخرى',
    name_en: 'Accum. Dep. Other Assets',
    type: 'ASSET',
    parent_code: '1300',
    is_group: false,
    requires_cost_center: false,
    normal_balance: 'CREDIT',
  },

  // ─── 2000 Liabilities ────────────────────────────────────────
  {
    code: '2000',
    name_ar: 'الالتزامات',
    name_en: 'Liabilities',
    type: 'LIABILITY',
    parent_code: null,
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '2100',
    name_ar: 'الالتزامات المتداولة',
    name_en: 'Current Liabilities',
    type: 'LIABILITY',
    parent_code: '2000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '2110',
    name_ar: 'الموردون',
    name_en: 'Suppliers',
    type: 'LIABILITY',
    parent_code: '2100',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '2111',
    name_ar: 'موردو القرطاسية',
    name_en: 'Stationery Suppliers',
    type: 'LIABILITY',
    parent_code: '2110',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2112',
    name_ar: 'موردو الأجهزة',
    name_en: 'Equipment Suppliers',
    type: 'LIABILITY',
    parent_code: '2110',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2113',
    name_ar: 'موردو الخدمات',
    name_en: 'Service Suppliers',
    type: 'LIABILITY',
    parent_code: '2110',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2114',
    name_ar: 'موردون آخرون',
    name_en: 'Other Suppliers',
    type: 'LIABILITY',
    parent_code: '2110',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2120',
    name_ar: 'المصروفات المستحقة',
    name_en: 'Accrued Expenses',
    type: 'LIABILITY',
    parent_code: '2100',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '2121',
    name_ar: 'رواتب مستحقة',
    name_en: 'Accrued Salaries',
    type: 'LIABILITY',
    parent_code: '2120',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2122',
    name_ar: 'أجور محاضرين مستحقة',
    name_en: 'Accrued Lecturer Fees',
    type: 'LIABILITY',
    parent_code: '2120',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2123',
    name_ar: 'كهرباء مستحقة',
    name_en: 'Accrued Electricity',
    type: 'LIABILITY',
    parent_code: '2120',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2124',
    name_ar: 'ماء مستحق',
    name_en: 'Accrued Water',
    type: 'LIABILITY',
    parent_code: '2120',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2125',
    name_ar: 'اتصالات وإنترنت مستحقة',
    name_en: 'Accrued Telecom',
    type: 'LIABILITY',
    parent_code: '2120',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2126',
    name_ar: 'صيانة مستحقة',
    name_en: 'Accrued Maintenance',
    type: 'LIABILITY',
    parent_code: '2120',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2127',
    name_ar: 'خدمات مستحقة',
    name_en: 'Accrued Services',
    type: 'LIABILITY',
    parent_code: '2120',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2128',
    name_ar: 'مصروفات مستحقة أخرى',
    name_en: 'Other Accrued Expenses',
    type: 'LIABILITY',
    parent_code: '2120',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2130',
    name_ar: 'الاستقطاعات والأمانات',
    name_en: 'Deductions & Deposits',
    type: 'LIABILITY',
    parent_code: '2100',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '2131',
    name_ar: 'استقطاعات الموظفين',
    name_en: 'Employee Deductions',
    type: 'LIABILITY',
    parent_code: '2130',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2132',
    name_ar: 'استقطاعات السلف',
    name_en: 'Advance Deductions',
    type: 'LIABILITY',
    parent_code: '2130',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2133',
    name_ar: 'أمانات الطلبة',
    name_en: 'Student Deposits',
    type: 'LIABILITY',
    parent_code: '2130',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2134',
    name_ar: 'تأمينات مستلمة',
    name_en: 'Security Deposits Received',
    type: 'LIABILITY',
    parent_code: '2130',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2135',
    name_ar: 'مبالغ مستلمة مقدماً',
    name_en: 'Amounts Received in Advance',
    type: 'LIABILITY',
    parent_code: '2130',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2200',
    name_ar: 'الالتزامات طويلة الأجل',
    name_en: 'Long-term Liabilities',
    type: 'LIABILITY',
    parent_code: '2000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '2210',
    name_ar: 'قروض طويلة الأجل',
    name_en: 'Long-term Loans',
    type: 'LIABILITY',
    parent_code: '2200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '2220',
    name_ar: 'التزامات طويلة الأجل أخرى',
    name_en: 'Other Long-term Liabilities',
    type: 'LIABILITY',
    parent_code: '2200',
    is_group: false,
    requires_cost_center: false,
  },

  // ─── 3000 Equity ─────────────────────────────────────────────
  {
    code: '3000',
    name_ar: 'حقوق الملكية وصافي الأصول',
    name_en: 'Equity & Net Assets',
    type: 'EQUITY',
    parent_code: null,
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '3100',
    name_ar: 'رأس المال أو التمويل',
    name_en: 'Capital / Funding',
    type: 'EQUITY',
    parent_code: '3000',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '3200',
    name_ar: 'الفائض المتراكم',
    name_en: 'Accumulated Surplus',
    type: 'EQUITY',
    parent_code: '3000',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '3300',
    name_ar: 'عجز أو فائض السنوات السابقة',
    name_en: 'Prior Years Surplus/Deficit',
    type: 'EQUITY',
    parent_code: '3000',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '3400',
    name_ar: 'نتيجة السنة المالية',
    name_en: 'Current Year Result',
    type: 'EQUITY',
    parent_code: '3000',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '3500',
    name_ar: 'احتياطيات',
    name_en: 'Reserves',
    type: 'EQUITY',
    parent_code: '3000',
    is_group: false,
    requires_cost_center: false,
  },

  // ─── 4000 Revenue ────────────────────────────────────────────
  {
    code: '4000',
    name_ar: 'الإيرادات',
    name_en: 'Revenue',
    type: 'REVENUE',
    parent_code: null,
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '4100',
    name_ar: 'إيرادات الطلبة',
    name_en: 'Student Revenue',
    type: 'REVENUE',
    parent_code: '4000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '4110',
    name_ar: 'إيرادات الأقساط الدراسية',
    name_en: 'Tuition Fees',
    type: 'REVENUE',
    parent_code: '4100',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '4111',
    name_ar: 'أقساط الدراسة الصباحية',
    name_en: 'Morning Tuition',
    type: 'REVENUE',
    parent_code: '4110',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4112',
    name_ar: 'أقساط الدراسة المسائية',
    name_en: 'Evening Tuition',
    type: 'REVENUE',
    parent_code: '4110',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4113',
    name_ar: 'أقساط البرامج أو الدورات الخاصة',
    name_en: 'Special Programs Tuition',
    type: 'REVENUE',
    parent_code: '4110',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4120',
    name_ar: 'رسوم التسجيل',
    name_en: 'Registration Fees',
    type: 'REVENUE',
    parent_code: '4100',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4130',
    name_ar: 'رسوم الامتحانات',
    name_en: 'Exam Fees',
    type: 'REVENUE',
    parent_code: '4100',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4140',
    name_ar: 'رسوم الوثائق والتأييدات',
    name_en: 'Document Fees',
    type: 'REVENUE',
    parent_code: '4100',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4150',
    name_ar: 'رسوم الهوية الطلابية',
    name_en: 'Student ID Fees',
    type: 'REVENUE',
    parent_code: '4100',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4160',
    name_ar: 'رسوم المختبرات',
    name_en: 'Lab Fees',
    type: 'REVENUE',
    parent_code: '4100',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4170',
    name_ar: 'رسوم النقل',
    name_en: 'Transport Fees',
    type: 'REVENUE',
    parent_code: '4100',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4180',
    name_ar: 'رسوم الأنشطة الطلابية',
    name_en: 'Student Activity Fees',
    type: 'REVENUE',
    parent_code: '4100',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4190',
    name_ar: 'إيرادات طلابية أخرى',
    name_en: 'Other Student Revenue',
    type: 'REVENUE',
    parent_code: '4100',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4200',
    name_ar: 'إيرادات الدورات والخدمات',
    name_en: 'Courses & Services Revenue',
    type: 'REVENUE',
    parent_code: '4000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '4210',
    name_ar: 'إيرادات الدورات التدريبية',
    name_en: 'Training Courses Revenue',
    type: 'REVENUE',
    parent_code: '4200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4220',
    name_ar: 'إيرادات الورش والمؤتمرات',
    name_en: 'Workshops & Conferences',
    type: 'REVENUE',
    parent_code: '4200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4230',
    name_ar: 'إيرادات الاستشارات',
    name_en: 'Consulting Revenue',
    type: 'REVENUE',
    parent_code: '4200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4240',
    name_ar: 'إيرادات تأجير القاعات',
    name_en: 'Hall Rental Revenue',
    type: 'REVENUE',
    parent_code: '4200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4250',
    name_ar: 'إيرادات الخدمات الإلكترونية',
    name_en: 'E-Services Revenue',
    type: 'REVENUE',
    parent_code: '4200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4260',
    name_ar: 'إيرادات خدمات أخرى',
    name_en: 'Other Services Revenue',
    type: 'REVENUE',
    parent_code: '4200',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4300',
    name_ar: 'المنح والتبرعات',
    name_en: 'Grants & Donations',
    type: 'REVENUE',
    parent_code: '4000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '4310',
    name_ar: 'المنح',
    name_en: 'Grants',
    type: 'REVENUE',
    parent_code: '4300',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4320',
    name_ar: 'التبرعات',
    name_en: 'Donations',
    type: 'REVENUE',
    parent_code: '4300',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4330',
    name_ar: 'دعم الأنشطة',
    name_en: 'Activity Support',
    type: 'REVENUE',
    parent_code: '4300',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4340',
    name_ar: 'دعم المشاريع',
    name_en: 'Project Support',
    type: 'REVENUE',
    parent_code: '4300',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4400',
    name_ar: 'إيرادات أخرى',
    name_en: 'Other Revenue',
    type: 'REVENUE',
    parent_code: '4000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '4410',
    name_ar: 'إيرادات بيع موجودات',
    name_en: 'Asset Sale Revenue',
    type: 'REVENUE',
    parent_code: '4400',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4420',
    name_ar: 'فروقات مالية دائنة',
    name_en: 'Credit Financial Differences',
    type: 'REVENUE',
    parent_code: '4400',
    is_group: false,
    requires_cost_center: false,
  },
  {
    code: '4430',
    name_ar: 'إيرادات متنوعة',
    name_en: 'Miscellaneous Revenue',
    type: 'REVENUE',
    parent_code: '4400',
    is_group: false,
    requires_cost_center: false,
  },

  // ─── 5000 Expenses ───────────────────────────────────────────
  {
    code: '5000',
    name_ar: 'المصروفات',
    name_en: 'Expenses',
    type: 'EXPENSE',
    parent_code: null,
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '5100',
    name_ar: 'مصروفات الرواتب والأجور',
    name_en: 'Salaries & Wages',
    type: 'EXPENSE',
    parent_code: '5000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '5110',
    name_ar: 'رواتب التدريسيين',
    name_en: 'Teachers Salaries',
    type: 'EXPENSE',
    parent_code: '5100',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5120',
    name_ar: 'رواتب الموظفين',
    name_en: 'Staff Salaries',
    type: 'EXPENSE',
    parent_code: '5100',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5130',
    name_ar: 'أجور المحاضرين',
    name_en: 'Lecturer Fees',
    type: 'EXPENSE',
    parent_code: '5100',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5140',
    name_ar: 'أجور العاملين بعقود',
    name_en: 'Contract Workers',
    type: 'EXPENSE',
    parent_code: '5100',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5150',
    name_ar: 'مكافآت',
    name_en: 'Bonuses',
    type: 'EXPENSE',
    parent_code: '5100',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5160',
    name_ar: 'مخصصات',
    name_en: 'Allowances',
    type: 'EXPENSE',
    parent_code: '5100',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5170',
    name_ar: 'أجور إضافية',
    name_en: 'Overtime',
    type: 'EXPENSE',
    parent_code: '5100',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5180',
    name_ar: 'مصروفات رواتب أخرى',
    name_en: 'Other Salary Expenses',
    type: 'EXPENSE',
    parent_code: '5100',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5200',
    name_ar: 'مصروفات الصيانة والترميم',
    name_en: 'Maintenance & Repairs',
    type: 'EXPENSE',
    parent_code: '5000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '5210',
    name_ar: 'صيانة المباني',
    name_en: 'Building Maintenance',
    type: 'EXPENSE',
    parent_code: '5200',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5220',
    name_ar: 'ترميم المباني',
    name_en: 'Building Renovation',
    type: 'EXPENSE',
    parent_code: '5200',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5230',
    name_ar: 'صيانة الأجهزة',
    name_en: 'Equipment Maintenance',
    type: 'EXPENSE',
    parent_code: '5200',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5240',
    name_ar: 'صيانة الحاسبات',
    name_en: 'Computer Maintenance',
    type: 'EXPENSE',
    parent_code: '5200',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5250',
    name_ar: 'صيانة المختبرات',
    name_en: 'Lab Maintenance',
    type: 'EXPENSE',
    parent_code: '5200',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5260',
    name_ar: 'صيانة المركبات',
    name_en: 'Vehicle Maintenance',
    type: 'EXPENSE',
    parent_code: '5200',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5270',
    name_ar: 'صيانة شبكات واتصالات',
    name_en: 'Network Maintenance',
    type: 'EXPENSE',
    parent_code: '5200',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5280',
    name_ar: 'صيانة أخرى',
    name_en: 'Other Maintenance',
    type: 'EXPENSE',
    parent_code: '5200',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5300',
    name_ar: 'القرطاسية والتجهيزات',
    name_en: 'Stationery & Supplies',
    type: 'EXPENSE',
    parent_code: '5000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '5310',
    name_ar: 'قرطاسية مكتبية',
    name_en: 'Office Stationery',
    type: 'EXPENSE',
    parent_code: '5300',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5320',
    name_ar: 'مطبوعات',
    name_en: 'Printing',
    type: 'EXPENSE',
    parent_code: '5300',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5330',
    name_ar: 'أحبار وطابعات',
    name_en: 'Ink & Printers',
    type: 'EXPENSE',
    parent_code: '5300',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5340',
    name_ar: 'مستلزمات تعليمية',
    name_en: 'Teaching Supplies',
    type: 'EXPENSE',
    parent_code: '5300',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5350',
    name_ar: 'مستلزمات مختبرية',
    name_en: 'Lab Supplies',
    type: 'EXPENSE',
    parent_code: '5300',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5360',
    name_ar: 'تجهيزات مكتبية صغيرة',
    name_en: 'Small Office Supplies',
    type: 'EXPENSE',
    parent_code: '5300',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5370',
    name_ar: 'مواد تنظيف',
    name_en: 'Cleaning Materials',
    type: 'EXPENSE',
    parent_code: '5300',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5380',
    name_ar: 'تجهيزات أخرى',
    name_en: 'Other Supplies',
    type: 'EXPENSE',
    parent_code: '5300',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5400',
    name_ar: 'الخدمات والعمالة الخارجية',
    name_en: 'Outsourced Services',
    type: 'EXPENSE',
    parent_code: '5000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '5410',
    name_ar: 'خدمات تنظيف',
    name_en: 'Cleaning Services',
    type: 'EXPENSE',
    parent_code: '5400',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5420',
    name_ar: 'خدمات حراسة',
    name_en: 'Security Services',
    type: 'EXPENSE',
    parent_code: '5400',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5430',
    name_ar: 'عمالة خارجية',
    name_en: 'External Labor',
    type: 'EXPENSE',
    parent_code: '5400',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5440',
    name_ar: 'خدمات استشارية',
    name_en: 'Consulting Services',
    type: 'EXPENSE',
    parent_code: '5400',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5450',
    name_ar: 'خدمات تقنية',
    name_en: 'IT Services',
    type: 'EXPENSE',
    parent_code: '5400',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5460',
    name_ar: 'خدمات قانونية',
    name_en: 'Legal Services',
    type: 'EXPENSE',
    parent_code: '5400',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5470',
    name_ar: 'خدمات محاسبية',
    name_en: 'Accounting Services',
    type: 'EXPENSE',
    parent_code: '5400',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5480',
    name_ar: 'خدمات أخرى',
    name_en: 'Other Services',
    type: 'EXPENSE',
    parent_code: '5400',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5500',
    name_ar: 'النقل والمحروقات',
    name_en: 'Transport & Fuel',
    type: 'EXPENSE',
    parent_code: '5000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '5510',
    name_ar: 'محروقات',
    name_en: 'Fuel',
    type: 'EXPENSE',
    parent_code: '5500',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5520',
    name_ar: 'صيانة وسائل النقل',
    name_en: 'Transport Maintenance',
    type: 'EXPENSE',
    parent_code: '5500',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5530',
    name_ar: 'أجور نقل',
    name_en: 'Transport Fees',
    type: 'EXPENSE',
    parent_code: '5500',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5540',
    name_ar: 'إيجار مركبات',
    name_en: 'Vehicle Rental',
    type: 'EXPENSE',
    parent_code: '5500',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5550',
    name_ar: 'مصروفات نقل أخرى',
    name_en: 'Other Transport Expenses',
    type: 'EXPENSE',
    parent_code: '5500',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5600',
    name_ar: 'الإعلام والتسويق',
    name_en: 'Media & Marketing',
    type: 'EXPENSE',
    parent_code: '5000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '5610',
    name_ar: 'إعلانات',
    name_en: 'Advertising',
    type: 'EXPENSE',
    parent_code: '5600',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5620',
    name_ar: 'حملات تسويقية',
    name_en: 'Marketing Campaigns',
    type: 'EXPENSE',
    parent_code: '5600',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5630',
    name_ar: 'إدارة مواقع التواصل',
    name_en: 'Social Media Management',
    type: 'EXPENSE',
    parent_code: '5600',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5640',
    name_ar: 'تصوير وإنتاج إعلامي',
    name_en: 'Media Production',
    type: 'EXPENSE',
    parent_code: '5600',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5650',
    name_ar: 'مطبوعات دعائية',
    name_en: 'Promotional Materials',
    type: 'EXPENSE',
    parent_code: '5600',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5660',
    name_ar: 'معارض ومشاركات',
    name_en: 'Exhibitions',
    type: 'EXPENSE',
    parent_code: '5600',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5670',
    name_ar: 'مصروفات إعلامية أخرى',
    name_en: 'Other Media Expenses',
    type: 'EXPENSE',
    parent_code: '5600',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5700',
    name_ar: 'الخدمات العامة والتشغيل',
    name_en: 'Utilities & Operations',
    type: 'EXPENSE',
    parent_code: '5000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '5710',
    name_ar: 'الكهرباء',
    name_en: 'Electricity',
    type: 'EXPENSE',
    parent_code: '5700',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5720',
    name_ar: 'الماء',
    name_en: 'Water',
    type: 'EXPENSE',
    parent_code: '5700',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5730',
    name_ar: 'الإنترنت',
    name_en: 'Internet',
    type: 'EXPENSE',
    parent_code: '5700',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5740',
    name_ar: 'الهاتف والاتصالات',
    name_en: 'Phone & Telecom',
    type: 'EXPENSE',
    parent_code: '5700',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5750',
    name_ar: 'الإيجارات',
    name_en: 'Rent',
    type: 'EXPENSE',
    parent_code: '5700',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5760',
    name_ar: 'اشتراكات البرامج والأنظمة',
    name_en: 'Software Subscriptions',
    type: 'EXPENSE',
    parent_code: '5700',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5770',
    name_ar: 'رسوم حكومية',
    name_en: 'Government Fees',
    type: 'EXPENSE',
    parent_code: '5700',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5780',
    name_ar: 'خدمات مصرفية',
    name_en: 'Bank Charges',
    type: 'EXPENSE',
    parent_code: '5700',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5790',
    name_ar: 'مصروفات تشغيلية أخرى',
    name_en: 'Other Operating Expenses',
    type: 'EXPENSE',
    parent_code: '5700',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5800',
    name_ar: 'الأنشطة الأكاديمية والطلابية',
    name_en: 'Academic & Student Activities',
    type: 'EXPENSE',
    parent_code: '5000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '5810',
    name_ar: 'مؤتمرات',
    name_en: 'Conferences',
    type: 'EXPENSE',
    parent_code: '5800',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5820',
    name_ar: 'ورش وندوات',
    name_en: 'Workshops & Seminars',
    type: 'EXPENSE',
    parent_code: '5800',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5830',
    name_ar: 'أنشطة طلابية',
    name_en: 'Student Activities',
    type: 'EXPENSE',
    parent_code: '5800',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5840',
    name_ar: 'مسابقات وجوائز',
    name_en: 'Contests & Awards',
    type: 'EXPENSE',
    parent_code: '5800',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5850',
    name_ar: 'ضيافة',
    name_en: 'Hospitality',
    type: 'EXPENSE',
    parent_code: '5800',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5860',
    name_ar: 'سفر وإيفاد',
    name_en: 'Travel & Secondment',
    type: 'EXPENSE',
    parent_code: '5800',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5870',
    name_ar: 'بحوث ومشاريع',
    name_en: 'Research & Projects',
    type: 'EXPENSE',
    parent_code: '5800',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5880',
    name_ar: 'أنشطة أخرى',
    name_en: 'Other Activities',
    type: 'EXPENSE',
    parent_code: '5800',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5900',
    name_ar: 'مصروفات أخرى',
    name_en: 'Other Expenses',
    type: 'EXPENSE',
    parent_code: '5000',
    is_group: true,
    requires_cost_center: false,
  },
  {
    code: '5910',
    name_ar: 'إهلاك الأصول',
    name_en: 'Depreciation',
    type: 'EXPENSE',
    parent_code: '5900',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5920',
    name_ar: 'خسائر بيع أصول',
    name_en: 'Loss on Asset Sale',
    type: 'EXPENSE',
    parent_code: '5900',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5930',
    name_ar: 'فروقات مالية مدينة',
    name_en: 'Debit Financial Differences',
    type: 'EXPENSE',
    parent_code: '5900',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5940',
    name_ar: 'ديون معدومة',
    name_en: 'Bad Debts',
    type: 'EXPENSE',
    parent_code: '5900',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5950',
    name_ar: 'مصروفات سنوات سابقة',
    name_en: 'Prior Year Expenses',
    type: 'EXPENSE',
    parent_code: '5900',
    is_group: false,
    requires_cost_center: true,
  },
  {
    code: '5960',
    name_ar: 'مصروفات متنوعة',
    name_en: 'Miscellaneous Expenses',
    type: 'EXPENSE',
    parent_code: '5900',
    is_group: false,
    requires_cost_center: true,
  },
];

export const COLLEGE_CHART_SEED: SeedAccountDef[] =
  assignSiblingSortOrders(COLLEGE_CHART_SEED_RAW);
