/** مصروفات تشغيلية مباشرة — لا تنشئ حركة دفتر مورد. */
import { acquireAccountingResourceLocks, bankAccountLock, cashboxLock, cashSessionLock, directExpenseLock, glAccountLock } from './accounting-locks';
import { AccountsHttpError } from './auth';
import { createBankVoucher, loadBankVoucher, postBankVoucher, voidBankVoucher } from './bank-vouchers';
import { assertCashSessionOptimisticConcurrency } from './cash-session-concurrency';
import { createCashVoucher, loadCashVoucher, postCashVoucher, voidCashVoucher } from './cash-vouchers';
import { normalizeCurrencyCode } from './currency';
import { nextDocumentNumber, pgDateOnly, yearLabelFromDate } from './document-sequences';
import { assertFiscalContextForEntry } from './journal-entries';
import { moneyIsPositive, normalizeMoneyInput } from './money';
import { assertValidExpenseGlAccount } from './supplier-invoice-types';
import { loadDirectExpenseType } from './direct-expense-types';
import { loadSupplier } from './suppliers';
import type { TxClient } from './with-transaction';
import { txQuery } from './with-transaction';

export type DirectExpenseRow = {
  id:string; expense_number:string; expense_date:Date|string; supplier_id:string|null; expense_type_id:string|null;
  expense_gl_account_id:string; cost_center_id:string|null; fiscal_year_id:string; fiscal_period_id:string;
  amount:string; currency_code:string; payment_method:'CASH'|'BANK'; cash_box_id:string|null; cash_box_session_id:string|null;
  bank_account_id:string|null; cash_voucher_id:string|null; bank_voucher_id:string|null; beneficiary_name:string;
  external_reference:string|null; description:string; status:'DRAFT'|'POSTED'|'VOID'; posted_at:Date|string|null; posted_by:string|null;
  voided_at:Date|string|null; voided_by:string|null; void_reason:string|null; created_by:string; updated_by:string|null;
  created_at:Date|string; updated_at:Date|string; version:number;
};
const iso=(v:Date|string|null|undefined)=>v==null?null:v instanceof Date?v.toISOString():new Date(String(v)).toISOString();
const txt=(v:unknown,n:number)=>{const s=String(v??'').trim().slice(0,n);return s||null;};
function opt(r:DirectExpenseRow,v:unknown,u:unknown){assertCashSessionOptimisticConcurrency({currentVersion:r.version,currentUpdatedAt:r.updated_at,expectedVersion:v,expectedUpdatedAt:u});}
function money(v:unknown){try{const x=normalizeMoneyInput(v);if(!moneyIsPositive(x))throw new Error();return x;}catch{throw new AccountsHttpError('مبلغ المصروف يجب أن يكون أكبر من صفر',400);}}
function iqd(v:unknown){const c=normalizeCurrencyCode(v,'IQD');if(c!=='IQD')throw new AccountsHttpError('عملة المصروف المباشر هي IQD فقط',400);return c;}
async function fiscal(c:TxClient,d:string){const r=await txQuery<{year_id:string;period_id:string}>(c,`SELECT y.id year_id,p.id period_id FROM accounts.fiscal_years y JOIN accounts.fiscal_periods p ON p.fiscal_year_id=y.id WHERE y.status='ACTIVE' AND p.status='OPEN' AND p.start_date<=$1::date AND p.end_date>=$1::date ORDER BY y.is_default DESC,p.start_date LIMIT 1`,[d]);if(!r.rows[0])throw new AccountsHttpError('لا توجد فترة مالية مفتوحة تغطي تاريخ المصروف',409);return r.rows[0];}
async function sequence(c:TxClient,y:string){const r=await txQuery<{start_date:string}>(c,`SELECT start_date::text start_date FROM accounts.fiscal_years WHERE id=$1::uuid`,[y]);if(!r.rows[0])throw new AccountsHttpError('السنة المالية غير موجودة',404);await txQuery(c,`INSERT INTO accounts.document_sequences(document_type,fiscal_year_id,prefix,current_number,padding_length,reset_yearly,is_active) SELECT 'DIRECT_EXPENSE',$1::uuid,'DEX',0,6,TRUE,TRUE WHERE NOT EXISTS(SELECT 1 FROM accounts.document_sequences WHERE document_type='DIRECT_EXPENSE' AND fiscal_year_id=$1::uuid)`,[y]);return(await nextDocumentNumber(c,{documentType:'DIRECT_EXPENSE',fiscalYearId:y,yearLabel:yearLabelFromDate(r.rows[0].start_date)})).formatted;}
async function cc(c:TxClient,id:string|null){if(!id)return;const r=await txQuery(c,`SELECT 1 FROM accounts.cost_centers WHERE id=$1::uuid AND is_active=TRUE`,[id]);if(!r.rows[0])throw new AccountsHttpError('مركز الكلفة غير موجود أو غير فعّال',400);}
async function resolved(c:TxClient,p:Record<string,unknown>,existing?:DirectExpenseRow){let typeId=existing?.expense_type_id??null, requires=false, defaultGl:string|null=null,defaultCc:string|null=null;if(p.expense_type_id!==undefined){typeId=txt(p.expense_type_id,100);if(typeId){const t=await loadDirectExpenseType(c,typeId,true);if(!t.is_active)throw new AccountsHttpError('نوع المصروف غير فعّال',409);requires=t.requires_cost_center;defaultGl=t.default_expense_gl_account_id;defaultCc=t.default_cost_center_id;}}else if(typeId){const t=await loadDirectExpenseType(c,typeId,false);requires=t.requires_cost_center;defaultGl=t.default_expense_gl_account_id;defaultCc=t.default_cost_center_id;}let gl=existing?.expense_gl_account_id??defaultGl;if(p.expense_gl_account_id!==undefined)gl=txt(p.expense_gl_account_id,100);gl=gl??defaultGl;if(!gl)throw new AccountsHttpError('حساب المصروف مطلوب',400);const g=await assertValidExpenseGlAccount(c,gl);let center=existing?.cost_center_id??defaultCc;if(p.cost_center_id!==undefined)center=txt(p.cost_center_id,100);if((requires||g.requires_cost_center)&&!center)throw new AccountsHttpError('مركز الكلفة مطلوب لهذا المصروف',400);await cc(c,center);return{typeId,gl:g.id,center};}

export function serializeDirectExpense(r:DirectExpenseRow){return{...r,expense_date:pgDateOnly(r.expense_date),amount:normalizeMoneyInput(r.amount),posted_at:iso(r.posted_at),voided_at:iso(r.voided_at),created_at:iso(r.created_at)!,updated_at:iso(r.updated_at)!};}
export async function loadDirectExpense(c:TxClient,id:string,forUpdate=false){const r=await txQuery<DirectExpenseRow>(c,`SELECT * FROM accounts.direct_expenses WHERE id=$1::uuid ${forUpdate?'FOR UPDATE':''}`,[id]);if(!r.rows[0])throw new AccountsHttpError('المصروف المباشر غير موجود',404);return r.rows[0];}
export async function createDirectExpense(c:TxClient,input:Record<string,unknown>&{created_by:string}){const date=input.expense_date?pgDateOnly(String(input.expense_date)):pgDateOnly(new Date()),f=await fiscal(c,date);await assertFiscalContextForEntry(c,{fiscalYearId:f.year_id,fiscalPeriodId:f.period_id,entryDate:date});const x=await resolved(c,input);const supplier=txt(input.supplier_id,100);if(supplier)await loadSupplier(c,supplier);const m=String(input.payment_method??'').toUpperCase();if(m!=='CASH'&&m!=='BANK')throw new AccountsHttpError('طريقة الدفع غير صالحة',400);const cash=txt(input.cash_box_id,100),session=txt(input.cash_box_session_id,100),bank=txt(input.bank_account_id,100);if(m==='CASH'&&(!cash||!session))throw new AccountsHttpError('الصندوق والجلسة مطلوبان للصرف النقدي',400);if(m==='BANK'&&!bank)throw new AccountsHttpError('الحساب المصرفي مطلوب للصرف المصرفي',400);const beneficiary=txt(input.beneficiary_name,200);if(!beneficiary)throw new AccountsHttpError('اسم المستفيد مطلوب',400);const r=await txQuery<DirectExpenseRow>(c,`INSERT INTO accounts.direct_expenses(expense_number,expense_date,supplier_id,expense_type_id,expense_gl_account_id,cost_center_id,fiscal_year_id,fiscal_period_id,amount,currency_code,payment_method,cash_box_id,cash_box_session_id,bank_account_id,beneficiary_name,external_reference,description,status,created_by,updated_by) VALUES($1,$2::date,$3::uuid,$4::uuid,$5::uuid,$6::uuid,$7::uuid,$8::uuid,$9::numeric,$10,$11,$12::uuid,$13::uuid,$14::uuid,$15,$16,$17,'DRAFT',$18::uuid,$18::uuid) RETURNING *`,[await sequence(c,f.year_id),date,supplier,x.typeId,x.gl,x.center,f.year_id,f.period_id,money(input.amount),iqd(input.currency_code),m,m==='CASH'?cash:null,m==='CASH'?session:null,m==='BANK'?bank:null,beneficiary,txt(input.external_reference,100),txt(input.description,4000)??'مصروف تشغيلي مباشر',input.created_by]);return r.rows[0];}
export async function updateDirectExpense(c:TxClient,p:Record<string,unknown>&{id:string;userId:string;version:unknown;updated_at:unknown}){const r=await loadDirectExpense(c,p.id,true);opt(r,p.version,p.updated_at);if(r.status!=='DRAFT')throw new AccountsHttpError('يمكن تعديل مسودات المصروفات فقط',409);const date=p.expense_date===undefined?pgDateOnly(r.expense_date):pgDateOnly(String(p.expense_date));const f=await fiscal(c,date);await assertFiscalContextForEntry(c,{fiscalYearId:f.year_id,fiscalPeriodId:f.period_id,entryDate:date});const x=await resolved(c,p,r);let supplier=r.supplier_id;if(p.supplier_id!==undefined){supplier=txt(p.supplier_id,100);if(supplier)await loadSupplier(c,supplier);}const a=p.amount===undefined?normalizeMoneyInput(r.amount):money(p.amount);const q=await txQuery<DirectExpenseRow>(c,`UPDATE accounts.direct_expenses SET expense_date=$2::date,supplier_id=$3::uuid,expense_type_id=$4::uuid,expense_gl_account_id=$5::uuid,cost_center_id=$6::uuid,fiscal_year_id=$7::uuid,fiscal_period_id=$8::uuid,amount=$9::numeric,beneficiary_name=$10,external_reference=$11,description=$12,updated_by=$13::uuid,updated_at=NOW(),version=version+1 WHERE id=$1::uuid RETURNING *`,[r.id,date,supplier,x.typeId,x.gl,x.center,f.year_id,f.period_id,a,p.beneficiary_name===undefined?r.beneficiary_name:txt(p.beneficiary_name,200)??r.beneficiary_name,p.external_reference===undefined?r.external_reference:txt(p.external_reference,100),p.description===undefined?r.description:txt(p.description,4000)??r.description,p.userId]);return q.rows[0];}
let __fault:null|'after_voucher'=null;export const setDirectExpensePostFaultForTests=(v:typeof __fault)=>{__fault=v;};
export async function postDirectExpense(c:TxClient,p:{id:string;userId:string;version:unknown;updated_at:unknown}){const peek=await loadDirectExpense(c,p.id,false);if(peek.status==='POSTED')return{expense:peek,created:false};await acquireAccountingResourceLocks(c,[directExpenseLock(peek.id),glAccountLock(peek.expense_gl_account_id),...(peek.payment_method==='CASH'?[cashboxLock(peek.cash_box_id!),cashSessionLock(peek.cash_box_session_id!)]:[bankAccountLock(peek.bank_account_id!)])]);const r=await loadDirectExpense(c,p.id,true);opt(r,p.version,p.updated_at);if(r.status!=='DRAFT')throw new AccountsHttpError('يمكن ترحيل مسودات المصروفات فقط',409);const x=await resolved(c,{expense_type_id:r.expense_type_id,expense_gl_account_id:r.expense_gl_account_id,cost_center_id:r.cost_center_id},r);const date=pgDateOnly(r.expense_date);await assertFiscalContextForEntry(c,{fiscalYearId:r.fiscal_year_id,fiscalPeriodId:r.fiscal_period_id,entryDate:date});let voucher:string;if(r.payment_method==='CASH'){const v=await createCashVoucher(c,{voucher_type:'CASH_PAYMENT',cash_box_id:r.cash_box_id,cash_box_session_id:r.cash_box_session_id,counter_account_id:x.gl,voucher_date:date,amount:r.amount,party_name:r.beneficiary_name,party_reference:r.expense_number,external_reference:r.external_reference,description:r.description,created_by:p.userId});voucher=(await postCashVoucher(c,{id:v.id,userId:p.userId,version:v.version,updated_at:v.updated_at})).voucher.id;}else{const v=await createBankVoucher(c,{voucher_type:'BANK_PAYMENT',bank_account_id:r.bank_account_id,counter_account_id:x.gl,voucher_date:date,amount:r.amount,party_name:r.beneficiary_name,party_reference:r.expense_number,external_reference:r.external_reference,description:r.description,currency_code:r.currency_code,created_by:p.userId});voucher=(await postBankVoucher(c,{id:v.id,userId:p.userId,version:v.version,updated_at:v.updated_at})).voucher.id;}if(__fault==='after_voucher')throw new Error('FAULT_AFTER_VOUCHER');const q=await txQuery<DirectExpenseRow>(c,`UPDATE accounts.direct_expenses SET status='POSTED',cash_voucher_id=CASE WHEN payment_method='CASH' THEN $2::uuid ELSE NULL END,bank_voucher_id=CASE WHEN payment_method='BANK' THEN $2::uuid ELSE NULL END,posted_by=$3::uuid,posted_at=NOW(),updated_by=$3::uuid,updated_at=NOW(),version=version+1 WHERE id=$1::uuid RETURNING *`,[r.id,voucher,p.userId]);return{expense:q.rows[0],created:true};}
export async function voidDirectExpense(c:TxClient,p:{id:string;userId:string;version:unknown;updated_at:unknown;reason?:unknown}){const r=await loadDirectExpense(c,p.id,true);opt(r,p.version,p.updated_at);if(r.status==='VOID')return r;if(r.status==='DRAFT'){const q=await txQuery<DirectExpenseRow>(c,`UPDATE accounts.direct_expenses SET status='VOID',void_reason=$2,voided_by=$3::uuid,voided_at=NOW(),updated_by=$3::uuid,updated_at=NOW(),version=version+1 WHERE id=$1::uuid RETURNING *`,[r.id,txt(p.reason,2000)??'إلغاء مسودة',p.userId]);return q.rows[0];}const reason=txt(p.reason,2000);if(!reason)throw new AccountsHttpError('سبب الإلغاء مطلوب للمصروف المرحّل',400);await acquireAccountingResourceLocks(c,[directExpenseLock(r.id),glAccountLock(r.expense_gl_account_id)]);if(r.payment_method==='CASH'&&r.cash_voucher_id){const v=await loadCashVoucher(c,r.cash_voucher_id,true);await voidCashVoucher(c,{id:v.id,userId:p.userId,version:v.version,updated_at:v.updated_at,reason});}else if(r.payment_method==='BANK'&&r.bank_voucher_id){const v=await loadBankVoucher(c,r.bank_voucher_id,true);await voidBankVoucher(c,{id:v.id,userId:p.userId,version:v.version,updated_at:v.updated_at,reason});}else throw new AccountsHttpError('المصروف المرحّل بلا سند صرف مرتبط',409);const q=await txQuery<DirectExpenseRow>(c,`UPDATE accounts.direct_expenses SET status='VOID',void_reason=$2,voided_by=$3::uuid,voided_at=NOW(),updated_by=$3::uuid,updated_at=NOW(),version=version+1 WHERE id=$1::uuid RETURNING *`,[r.id,reason,p.userId]);return q.rows[0];}
export async function listDirectExpenses(c:TxClient,p:{q?:string;status?:string|null;supplier_id?:string|null;expense_type_id?:string|null;payment_method?:string|null;page?:number;page_size?:number}){const page=Math.max(1,p.page??1),page_size=Math.min(100,Math.max(1,p.page_size??20)),v=[(p.q??'').trim(),p.status??null,p.supplier_id??null,p.expense_type_id??null,p.payment_method??null],where=`WHERE ($1='' OR de.expense_number ILIKE '%'||$1||'%' OR de.description ILIKE '%'||$1||'%' OR de.beneficiary_name ILIKE '%'||$1||'%') AND ($2::text IS NULL OR de.status=$2) AND ($3::uuid IS NULL OR de.supplier_id=$3::uuid) AND ($4::uuid IS NULL OR de.expense_type_id=$4::uuid) AND ($5::text IS NULL OR de.payment_method=$5)`;const n=await txQuery<{total:number}>(c,`SELECT COUNT(*)::int total FROM accounts.direct_expenses de ${where}`,v);const r=await txQuery<DirectExpenseRow>(c,`SELECT de.* FROM accounts.direct_expenses de ${where} ORDER BY de.expense_date DESC,de.created_at DESC LIMIT $6 OFFSET $7`,[...v,page_size,(page-1)*page_size]);return{rows:r.rows,total:n.rows[0]?.total??0,page,page_size};}
