import { NextRequest } from 'next/server';
import { AccountsHttpError, isAuthFailure, jsonError, jsonSuccess, mapPgError, requireAccountsAccess } from './auth';
import { writeFinancialAudit } from './audit';
import { withTransaction, acquireJournalEntriesLock } from './with-transaction';
import { SUPPLIER_PAYABLES_CAPABILITIES as C, assertSupplierPayablesCapability } from './supplier-payables-access';
import { createSupplierPayment, getSupplierPaymentDetail, listOpenSupplierInvoices, listSupplierPayments, loadSupplierPayment, postSupplierPayment, previewSupplierPaymentAllocation, serializeSupplierPayment, updateSupplierPayment, voidSupplierPayment } from './supplier-payments';
import { createDirectExpense, getDirectExpenseDetail, listDirectExpenses, loadDirectExpense, postDirectExpense, serializeDirectExpense, updateDirectExpense, voidDirectExpense } from './direct-expenses';
import { createDirectExpenseType, deactivateDirectExpenseType, listDirectExpenseTypes, loadDirectExpenseType, serializeDirectExpenseType, updateDirectExpenseType } from './direct-expense-types';
import { query } from '@/src/lib/db';

type Ctx={params:Promise<{id:string}>};
const fail=(e:unknown)=>e instanceof AccountsHttpError?jsonError(e.message,e.status):mapPgError(e);
const page=(x:string|null,d:number)=>Math.max(1,Number(x||d));
async function access(request:NextRequest,cap:string){const a=await requireAccountsAccess(request);if(isAuthFailure(a))return a;await assertSupplierPayablesCapability(null,a.user.id,cap);return a;}
export async function payments(request:NextRequest){
 const a=await access(request,request.method==='GET'?C.PAYMENTS_VIEW:C.PAYMENTS_PREPARE);if(isAuthFailure(a))return a.response;
 try{if(request.method==='GET'){const s=request.nextUrl.searchParams,r=await withTransaction(c=>listSupplierPayments(c,{q:s.get('q')||'',status:s.get('status'),supplier_account_id:s.get('supplier_account_id'),supplier_id:s.get('supplier_id'),payment_method:s.get('payment_method'),page:page(s.get('page'),1),page_size:Math.min(100,page(s.get('page_size'),20))}));return jsonSuccess({data:r.rows.map(serializeSupplierPayment),pagination:{page:r.page,page_size:r.page_size,total:r.total,total_pages:Math.ceil(r.total/r.page_size)||1}});}
 const b=await request.json(),r=await withTransaction(async c=>{const x=await createSupplierPayment(c,{...b,created_by:a.user.id});await writeFinancialAudit(c,{userId:a.user.id,action:'SUPPLIER_PAYMENT_CREATED',entityType:'supplier_payment',entityId:x.payment.id,newValues:{...serializeSupplierPayment(x.payment),allocations:x.allocations},description:`إنشاء دفعة مورد ${x.payment.payment_number}`,ipAddress:a.ipAddress,userAgent:a.userAgent});if(x.allocations.length)await writeFinancialAudit(c,{userId:a.user.id,action:'SUPPLIER_PAYMENT_ALLOCATED',entityType:'supplier_payment',entityId:x.payment.id,newValues:{allocations:x.allocations},description:`تخصيص دفعة مورد ${x.payment.payment_number}`,ipAddress:a.ipAddress,userAgent:a.userAgent});return x;});return jsonSuccess({data:{...serializeSupplierPayment(r.payment),allocations:r.allocations}},201);
 }catch(e){return fail(e);}
}
export async function payment(request:NextRequest,ctx:Ctx){
 const a=await access(request,request.method==='GET'?C.PAYMENTS_VIEW:C.PAYMENTS_PREPARE);if(isAuthFailure(a))return a.response;
 try{const{id}=await ctx.params;if(request.method==='GET'){const r=await withTransaction(c=>getSupplierPaymentDetail(c,id));return jsonSuccess({data:{...serializeSupplierPayment(r.payment),allocations:r.allocations,supplier_name_ar:r.supplier_name_ar,balance_before:r.balance_before,balance_after:r.balance_after,voucher_number:r.voucher_number,channel_label:r.channel_label}});} const b=await request.json(),r=await withTransaction(async c=>{const before=await getSupplierPaymentDetail(c,id);const x=await updateSupplierPayment(c,{id,userId:a.user.id,...b});await writeFinancialAudit(c,{userId:a.user.id,action:'SUPPLIER_PAYMENT_UPDATED',entityType:'supplier_payment',entityId:id,oldValues:before,newValues:{...serializeSupplierPayment(x.payment),allocations:x.allocations},description:`تعديل دفعة مورد ${x.payment.payment_number}`,ipAddress:a.ipAddress,userAgent:a.userAgent});if(b.allocations!==undefined)await writeFinancialAudit(c,{userId:a.user.id,action:'SUPPLIER_PAYMENT_ALLOCATED',entityType:'supplier_payment',entityId:id,oldValues:{allocations:before.allocations},newValues:{allocations:x.allocations},description:`إعادة تخصيص دفعة مورد ${x.payment.payment_number}`,ipAddress:a.ipAddress,userAgent:a.userAgent});return x;});return jsonSuccess({data:{...serializeSupplierPayment(r.payment),allocations:r.allocations}});}catch(e){return fail(e);}
}
export async function paymentPreview(request:NextRequest,ctx:Ctx){const a=await access(request,C.PAYMENTS_PREPARE);if(isAuthFailure(a))return a.response;try{const{id}=await ctx.params,b=await request.json().catch(()=>({}));const r=await withTransaction(async c=>{const p=await loadSupplierPayment(c,id);return previewSupplierPaymentAllocation(c,{supplierAccountId:String(b.supplier_account_id||p.supplier_account_id),amount:b.amount??p.amount,mode:b.mode==='manual'?'manual':'auto',allocations:b.allocations});});return jsonSuccess({data:r});}catch(e){return fail(e);}}
export async function paymentTransition(request:NextRequest,ctx:Ctx,action:'post'|'void'){const a=await access(request,action==='post'?C.PAYMENTS_POST:C.PAYMENTS_VOID);if(isAuthFailure(a))return a.response;try{const{id}=await ctx.params,b=await request.json().catch(()=>({}));const r=await withTransaction(async c=>{await acquireJournalEntriesLock(c);const before=await loadSupplierPayment(c,id);const x=action==='post'?await postSupplierPayment(c,{id,userId:a.user.id,...b}):await voidSupplierPayment(c,{id,userId:a.user.id,...b});const row='payment'in x?x.payment:x;await writeFinancialAudit(c,{userId:a.user.id,action:action==='post'?'SUPPLIER_PAYMENT_POSTED':'SUPPLIER_PAYMENT_VOIDED',entityType:'supplier_payment',entityId:id,oldValues:serializeSupplierPayment(before),newValues:serializeSupplierPayment(row),description:`${action==='post'?'ترحيل':'إلغاء'} دفعة مورد ${row.payment_number}`,ipAddress:a.ipAddress,userAgent:a.userAgent});return x;});const row='payment'in r?r.payment:r;return jsonSuccess({data:serializeSupplierPayment(row)});}catch(e){return fail(e);}}
export async function paymentOptions(request:NextRequest){const a=await access(request,C.PAYMENTS_VIEW);if(isAuthFailure(a))return a.response;try{const supplier=request.nextUrl.searchParams.get('supplier_account_id');const [invoices,sessions,boxes,banks]=await Promise.all([supplier?withTransaction(c=>listOpenSupplierInvoices(c,supplier)):Promise.resolve([]),query(`SELECT s.id,s.cash_box_id,s.session_date::text,cb.code cash_box_code,cb.name_ar cash_box_name_ar FROM accounts.cash_box_sessions s JOIN accounts.cash_boxes cb ON cb.id=s.cash_box_id WHERE s.status='OPEN' AND cb.status='ACTIVE' ORDER BY s.session_date DESC`),query(`SELECT id,code,name_ar FROM accounts.cash_boxes WHERE status='ACTIVE' ORDER BY code`),query(`SELECT id,code,account_name_ar,currency_code FROM accounts.bank_accounts WHERE status='ACTIVE' AND allows_payments=TRUE ORDER BY code`)]);return jsonSuccess({data:{open_invoices:invoices,open_sessions:sessions.rows,cash_boxes:boxes.rows,bank_accounts:banks.rows,payment_methods:[{code:'CASH',name_ar:'نقدي'},{code:'BANK',name_ar:'مصرفي'}]}});}catch(e){return fail(e);}}
export async function expenses(request:NextRequest){const a=await access(request,request.method==='GET'?C.DIRECT_EXPENSES_VIEW:C.DIRECT_EXPENSES_PREPARE);if(isAuthFailure(a))return a.response;try{if(request.method==='GET'){const s=request.nextUrl.searchParams,r=await withTransaction(c=>listDirectExpenses(c,{q:s.get('q')||'',status:s.get('status'),supplier_id:s.get('supplier_id'),expense_type_id:s.get('expense_type_id'),payment_method:s.get('payment_method'),page:page(s.get('page'),1),page_size:Math.min(100,page(s.get('page_size'),20))}));return jsonSuccess({data:r.rows.map(serializeDirectExpense),pagination:{page:r.page,page_size:r.page_size,total:r.total,total_pages:Math.ceil(r.total/r.page_size)||1}});}const b=await request.json(),r=await withTransaction(async c=>{const x=await createDirectExpense(c,{...b,created_by:a.user.id});await writeFinancialAudit(c,{userId:a.user.id,action:'DIRECT_EXPENSE_CREATED',entityType:'direct_expense',entityId:x.id,newValues:serializeDirectExpense(x),description:`إنشاء مصروف ${x.expense_number}`,ipAddress:a.ipAddress,userAgent:a.userAgent});return x;});return jsonSuccess({data:serializeDirectExpense(r)},201);}catch(e){return fail(e);}}
export async function expense(request:NextRequest,ctx:Ctx){const a=await access(request,request.method==='GET'?C.DIRECT_EXPENSES_VIEW:C.DIRECT_EXPENSES_PREPARE);if(isAuthFailure(a))return a.response;try{const{id}=await ctx.params;if(request.method==='GET'){const r=await withTransaction(c=>getDirectExpenseDetail(c,id));return jsonSuccess({data:{...serializeDirectExpense(r.expense),expense_type_name:r.expense_type_name,expense_gl_label:r.expense_gl_label,cost_center_label:r.cost_center_label,supplier_name_ar:r.supplier_name_ar,voucher_number:r.voucher_number,channel_label:r.channel_label}});}const b=await request.json(),r=await withTransaction(async c=>{const before=await loadDirectExpense(c,id);const x=await updateDirectExpense(c,{id,userId:a.user.id,...b});await writeFinancialAudit(c,{userId:a.user.id,action:'DIRECT_EXPENSE_UPDATED',entityType:'direct_expense',entityId:id,oldValues:serializeDirectExpense(before),newValues:serializeDirectExpense(x),description:`تعديل مصروف ${x.expense_number}`,ipAddress:a.ipAddress,userAgent:a.userAgent});return x;});return jsonSuccess({data:serializeDirectExpense(r)});}catch(e){return fail(e);}}
export async function expenseTransition(request:NextRequest,ctx:Ctx,action:'post'|'void'){const a=await access(request,action==='post'?C.DIRECT_EXPENSES_POST:C.DIRECT_EXPENSES_VOID);if(isAuthFailure(a))return a.response;try{const{id}=await ctx.params,b=await request.json().catch(()=>({}));const r=await withTransaction(async c=>{await acquireJournalEntriesLock(c);const before=await loadDirectExpense(c,id);const x=action==='post'?await postDirectExpense(c,{id,userId:a.user.id,...b}):await voidDirectExpense(c,{id,userId:a.user.id,...b});const row='expense'in x?x.expense:x;await writeFinancialAudit(c,{userId:a.user.id,action:action==='post'?'DIRECT_EXPENSE_POSTED':'DIRECT_EXPENSE_VOIDED',entityType:'direct_expense',entityId:id,oldValues:serializeDirectExpense(before),newValues:serializeDirectExpense(row),description:`${action==='post'?'ترحيل':'إلغاء'} مصروف ${row.expense_number}`,ipAddress:a.ipAddress,userAgent:a.userAgent});return row;});return jsonSuccess({data:serializeDirectExpense(r)});}catch(e){return fail(e);}}
export async function expenseTypes(request:NextRequest){const a=await access(request,request.method==='GET'?C.DIRECT_EXPENSES_VIEW:C.DIRECT_EXPENSE_TYPES_MANAGE);if(isAuthFailure(a))return a.response;try{if(request.method==='GET'){const s=request.nextUrl.searchParams,r=await withTransaction(c=>listDirectExpenseTypes(c,{q:s.get('q')||'',active_only:s.get('active_only')==='true',page:page(s.get('page'),1),page_size:Math.min(100,page(s.get('page_size'),50))}));return jsonSuccess({data:r.rows.map(serializeDirectExpenseType),pagination:r});}const b=await request.json(),r=await withTransaction(async c=>{const x=await createDirectExpenseType(c,{...b,created_by:a.user.id});await writeFinancialAudit(c,{userId:a.user.id,action:'DIRECT_EXPENSE_TYPE_CREATED',entityType:'direct_expense_type',entityId:x.id,newValues:serializeDirectExpenseType(x),description:`إنشاء نوع مصروف ${x.code}`,ipAddress:a.ipAddress,userAgent:a.userAgent});return x;});return jsonSuccess({data:serializeDirectExpenseType(r)},201);}catch(e){return fail(e);}}
export async function expenseType(request:NextRequest,ctx:Ctx,action?:'deactivate'){const a=await access(request,C.DIRECT_EXPENSE_TYPES_MANAGE);if(isAuthFailure(a))return a.response;try{const{id}=await ctx.params;if(request.method==='GET')return jsonSuccess({data:serializeDirectExpenseType(await withTransaction(c=>loadDirectExpenseType(c,id)))});const b=await request.json().catch(()=>({}));const r=await withTransaction(async c=>{const before=await loadDirectExpenseType(c,id);const x=action==='deactivate'?await deactivateDirectExpenseType(c,{id,userId:a.user.id,...b}):await updateDirectExpenseType(c,{id,userId:a.user.id,...b});await writeFinancialAudit(c,{userId:a.user.id,action:action?'DIRECT_EXPENSE_TYPE_DEACTIVATED':'DIRECT_EXPENSE_TYPE_UPDATED',entityType:'direct_expense_type',entityId:id,oldValues:serializeDirectExpenseType(before),newValues:serializeDirectExpenseType(x),description:`${action?'تعطيل':'تعديل'} نوع مصروف ${x.code}`,ipAddress:a.ipAddress,userAgent:a.userAgent});return x;});return jsonSuccess({data:serializeDirectExpenseType(r)});}catch(e){return fail(e);}}
